# Sample config for Prometheus.

global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:

  - job_name: ansible-for-vm
    static_configs:
      - targets: ["192.168.56.10:9100"]

  - job_name: grafana-metrics
    static_configs:
      - targets: ["192.168.56.11:9100"]

  - job_name: elk-agent-metrics
    static_configs:
      - targets: ["192.168.56.12:9100"]

  - job_name: backend
    static_configs:
      - targets: ["192.168.56.13:9100"]