- name: Install and config filebeat on VM
  hosts: elk-agent-metrics
  vars:
    filebeat_ubuntu: filebeat-7.15.1-amd64.deb

  tasks:
    - name: Install & config Filebeat on Ubuntu
      block:
        
        - name: Copy Filebeat
          copy:
            src: /vagrant/userdata/elk-stack/filebeat/ubuntu/{{ filebeat_ubuntu }}
            dest: /home/vagrant/
            owner: root
            group: root
            mode: '0644'
        
        - name: Install Filebeat
          apt:
            deb: /home/vagrant/{{ filebeat_ubuntu }}
            state: present 
        
        - name: Enable system module
          shell:
            cmd: "sudo filebeat modules enable system"

        - name: Copy filebeat.yml
          copy:
            src: /vagrant/userdata/elk-stack/filebeat/ubuntu/filebeat.yml
            dest: /etc/filebeat/
            owner: root
            group: root
            mode: '0644'

        - name: Copy system config module
          copy:
            src: /vagrant/userdata/elk-stack/filebeat/ubuntu/system.yml
            dest: /etc/filebeat/modules.d/
            owner: root
            group: root
            mode: '0644'
      
      when: ansible_os_family == "Debian"      

    - name: Shell configure pipeline
      block:

        - name: --pipelines
          shell:
            cmd: "sudo filebeat setup --pipelines --modules system"

        - name: --pipelines
          shell:
            cmd: f"sudo filebeat setup --index-management -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["192.168.56.12:9200"]'"

        - name: --pipelines
          shell:
            cmd: "sudo filebeat setup -E output.logstash.enabled=false -E output.elasticsearch.hosts=['192.168.56.12:9200'] -E setup.kibana.host=192.168.56.12:5601"

      when: ansible_os_family == "Debian"      

    - name: Start&Enable Filebeat
      block:
        - name: Start&Enable Filebeat
          service:
            name: filebeat.service
            state: started
            enabled: yes
      
      when: ansible_os_family == "Debian"      






    # - name: Install service on RedHat
    #   block:
    #     - name: Install tar
    #       yum:
    #         name: "{{item}}"
    #         state: present
    #       loop:
    #         - tar
    #   when: ansible_os_family == "RedHat"

    # 